### ISSUE TITLE
我可以在这问问题吗？请问启动了10分钟好像无事发生

### ISSUE THREAD

**Issue by zclikezc** [charlie-captain/MeowAI#2]
通过群晖和群晖系统安装启动的
cpu占用很低
也没有新的标签添加到相册
请问怎么确认程序是否在正常运行呀

**Comment by zclikezc** [comment]
搜索
meow - INFO - Load model: 4.35 s
meow - ERROR - Expecting value: line 1 column 1 (char 0)
meow - INFO - b'{"error":{"code":119},"success":false}'
meow - INFO - []
meow - ERROR - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/app/src/api/server.py", line 142, in read_done_list
    data = json.load(f, cls=DetectFileDecoder)
  File "/usr/local/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
meow - INFO - current offset = 0 limit = 100
meow - ERROR - b'{"error":{"code":119},"success":false}'
meow - ERROR - get_time_line failed:
meow - INFO - Sleep...
当前环境: Release
CurConfig = {}
meow - INFO - <src.config.config.Config object at 0x7f64ca4a2f10>
meow - INFO - 排除的场景: []
meow - INFO - 加载模型: yolov5m6
meow - INFO - CUDA is not available.
meow - INFO - MPS is not available.
YOLOv5 🚀 2023-4-2 Python-3.8.16 torch-1.13.0+cpu CPU
Fusing layers... 
[W NNPACK.cpp:53] Could not initialize NNPACK! Reason: Unsupported hardware.
YOLOv5m6 summary: 378 layers, 35704908 parameters, 0 gradients
Adding AutoShape... 
meow - INFO - 加载模型: 4.39 s
meow - ERROR - Expecting value: line 1 column 1 (char 0)
meow - INFO - b'{"error":{"code":119},"success":false}'
meow - INFO - []
meow - ERROR - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/app/src/api/server.py", line 142, in read_done_list
    data = json.load(f, cls=DetectFileDecoder)
  File "/usr/local/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
meow - INFO - current offset = 0 limit = 100
meow - ERROR - b'{"error":{"code":119},"success":false}'
meow - ERROR - get_time_line failed:
meow - INFO - Sleep...
meow - ERROR - get_time_line failed:
meow - INFO - Sleep...

**Comment by zclikezc** [comment]
![image](https://user-images.githubusercontent.com/54420519/234750103-ae1f9eba-1f46-48d0-bf33-7c4dc7896311.png)
![image](https://user-images.githubusercontent.com/54420519/234750153-97ecb809-9e5b-4319-9a33-b1f10ef314fb.png)

**Comment by zclikezc** [comment]
朋友说我没装python3
装了以后还是sleep了
![image](https://user-images.githubusercontent.com/54420519/234751705-f9e21269-a624-4702-ae79-c3462d584f62.png)

**Comment by zclikezc** [comment]
![image](https://user-images.githubusercontent.com/54420519/234753163-4ebea3b8-3369-4dea-b18c-6959f3cad953.png)

**Comment by zclikezc** [comment]
![image](https://user-images.githubusercontent.com/54420519/234754289-de54a068-a807-44e0-aa2d-1c226b927e13.png)

**Comment by charlie-captain** [comment]
应该是你的环境变量账号密码不对，检查user和pwd这两个参数是否正确

**Comment by Andrew55529** [comment]
Need go to Control Panal -> Portal for Enter -> Synology Photo -> And write "photo" on first field.

**Comment by charlie-captain** [comment]
> Need go to Control Panal -> Portal for Enter -> Synology Photo -> And write "photo" on first field.

Thanks, I have fixed this 354ce00233d1372cb8228e03e275818240eecea9, you can try it later.

**Comment by zclikezc** [comment]
是更新了嘛？谢谢

**Comment by charlie-captain** [comment]
> 是更新了嘛？谢谢

是的，直接拉取最新代码或者docker即可
