### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Andrew55529** [charlie-captain/MeowAI#5]
Can this ai track more then one object pre photo?

**Comment by charlie-captain** [comment]
> Can this ai track more then one object pre photo?

Yes, it does have the capability to recognize multiple objects. However, currently, I only retrieve the highest confidence object. Perhaps in the future, I can include the option to detect multiple objects. A single image can be associated with multiple labels. Do you have any other suggestions?

**Comment by Andrew55529** [comment]
As I understand it, the label with the highest probability is being taken now, but is there a lower bound? Will a label with a 10% chance be added?

Or it set by score_threshold = 0.7

**Comment by charlie-captain** [comment]
> As I understand it, the label with the highest probability is being taken now, but is there a lower bound? Will a label with a 10% chance be added?
> 
> Or it set by score_threshold = 0.7

Currently, only the recognition confidence above 0.7 will be added as a label.
