### ISSUE TITLE
普通用户权限登录

### ISSUE THREAD

**Issue by eritpchy** [charlie-captain/MeowAI#6]
> url = f'{base_url}/webapi/auth.cgi?api=SYNO.API.Auth&session=Foto&version=7&method=login&account={username}&passwd={pwd}&format=cookie&enable_syno_token=yes'

这个api 似乎需要管理员权限才能登录, 改成下面这样似乎可行, 不知道有没有啥问题.

> url = f'{base_url}/webapi/auth.cgi?api=SYNO.API.Auth&version=3&method=login&account={username}&passwd={pwd}&format=cookie&enable_syno_token=yes'

另外问问类似的方法能不能实现群晖搜索相片内的文字?

**Comment by eritpchy** [comment]
问题2 已实现

**Comment by charlie-captain** [comment]
> > url = f'{base_url}/webapi/auth.cgi?api=SYNO.API.Auth&session=Foto&version=7&method=login&account={username}&passwd={pwd}&format=cookie&enable_syno_token=yes'
> 
> 这个api 似乎需要管理员权限才能登录, 改成下面这样似乎可行, 不知道有没有啥问题.
> 
> > url = f'{base_url}/webapi/auth.cgi?api=SYNO.API.Auth&version=3&method=login&account={username}&passwd={pwd}&format=cookie&enable_syno_token=yes'
> 
> 另外问问类似的方法能不能实现群晖搜索相片内的文字?

1. 感谢，目前在DSM7测试没什么问题，先这样解决问题 f7196ec8632e1df8fa89d0d9beb134debc068cd5
2. 参考 https://github.com/N4S4/synology-api

**Comment by eritpchy** [comment]
可以ocr了, 参考 https://github.com/eritpchy/MeowAI-Paddle/commit/386de0732ac1bc827152d296134ffe2780db066f
