### ISSUE TITLE
请问一下python下怎么把标签设置成中文呢？

### ISSUE THREAD

**Issue by junevin1** [charlie-captain/MeowAI#8]
找了半天找不到如何调整

**Comment by charlie-captain** [comment]
readme参数说明
lang=zh

**Comment by junevin1** [comment]
请原谅我这个半文盲，我并不是不知道这个参数说明，但是我在windows下不知道如何把user="xxx" \pwd="xxx" \ mode="xxx" \这些参数运行到python，我用python main.py --user="vmvmv" --pwd="123456" --ip="192.168.6.114:53223" --mode="person",总是显示KeyError: 'user'，最后我只能在api.py里改，运行成功了，但是，api.py没找到lang这个参数，所以我不知道应该在哪里调整。感谢你的耐心回复，请问你能告诉我一个调整它的方法吗？

**Comment by charlie-captain** [comment]
user="xxx" \
 pwd="xxx" \
 mode="xxx" \
 exclude_class="[\"cat\"]" \
 ip="192.168.5.1:5000" \
 lang="zh" \
 python3 main.py
